### ISSUE TITLE
SubEdit & Patch UPK

### ISSUE THREAD

**Issue by locsucc** [deadYokai/dishonored-toolkit#2]
How to use SubEdit?
And when i patch upk using the files in _DYextracted, i get stuck on loading screen

**Comment by deadYokai** [comment]
> How to use SubEdit? And when i patch upk using the files in _DYextracted, i get stuck on loading screen

still under development

**Comment by deadYokai** [comment]
@loccacsuc 

#### Subtitles

- Export to yaml (from `INT` language)
    ```bash
    python3 subedit.py <upkfile> --output out.yaml
    ```
- Import to UPK
    ```bash
    python3 subedit.py <upkfile> --input in.yaml --langCode <LANG> --langReplace <LANG>
	```
	- `--langCode` - Language to replace (except `INT`, because i'm too lazy :P)
		- Avaiable codes:
			```
			CHN
			CZE
			DEU
			ESM
			ESN
			FRA
			HUN
			ITA
			JPN
			KOR
			POL
			RUS
			SLO
			```
	- `--langReplace` (optional) - Change language code to custom (3 chars)
	
	**A new `<upkfile>_patched` upk will be created at same dir as `<upkfile>`**
