### ISSUE TITLE
error when import export text SubEdit

### ISSUE THREAD

**Issue by locsucc** [deadYokai/dishonored-toolkit#4]
when I localize some text into Vietnamese and import to UPK file but when I export from that UPK file i had this error

**before import**
![image](https://github.com/deadYokai/dishonored-toolkit/assets/171554153/32f95739-b1dc-4eaa-b881-d00ec5c0a136)
**after**
![image](https://github.com/deadYokai/dishonored-toolkit/assets/171554153/c9e2cf0d-d262-4ff5-9a66-87320edddfcd)

**Comment by deadYokai** [comment]
check 639d4517e6a5d3fd85d84c1cb55bacf30a840dc1

**Comment by locsucc** [comment]
> check [639d451](https://github.com/deadYokai/dishonored-toolkit/commit/639d4517e6a5d3fd85d84c1cb55bacf30a840dc1)

luv u
