### ISSUE TITLE
[SubEdit] add PlayerChoice support

### ISSUE THREAD

**Issue by deadYokai** [deadYokai/dishonored-toolkit#5]

**Comment by deadYokai** [comment]
`NonWord` has a same structure as `Blurb`, porting not needed

**Comment by deadYokai** [comment]
closed by 940c3f91d5271f58f77dce293d974985677c2031

**Comment by locsucc** [comment]
can u also make a toolkit for dishonored 2 pleawe?

**Comment by deadYokai** [comment]
> can u also make a toolkit for dishonored 2 pleawe?

maybe in the future, after i finish this
