### ISSUE TITLE
Fix a `Assertion failed: i>=0 && (i<ArrayNum||(i==0 && ArrayNum==0))`

### ISSUE THREAD

**Issue by deadYokai** [deadYokai/dishonored-toolkit#6]
Game crashes when loading a DLC's

`Assertion failed: i>=0 && (i<ArrayNum||(i==0 && ArrayNum==0))`
caused by a modification a `DLC06_DishonoredGameFull_P.upk` in DLC06 _(maybe)_

**Comment by deadYokai** [comment]
Found mismatched size:
```
25159308  DLC06_DishonoredGameFull_P.upk
25300404  DLC06_DishonoredGameFull_P.upk_patched
```

**Comment by deadYokai** [comment]
1) Found bug with `INT` replacement [status: fixed :white_check_mark:  ]

2) Important: Need to rework offset writing in Textures ~~(may cause a crash)~~ [status: fixed :white_check_mark:  _kind of_ ]

**Comment by locsucc** [comment]
another error for u:
![image](https://github.com/user-attachments/assets/cbe8fb9e-9ada-46f0-9ef1-1c6ee49be076)

**Comment by locsucc** [comment]
subedit cant import upk
![image](https://github.com/user-attachments/assets/a206186d-4336-4500-89d9-f3fcba2208fd)

**Comment by locsucc** [comment]
@@
![image](https://github.com/user-attachments/assets/164fbdc4-8e57-429f-93a9-bd4e3ca8ad51)

**Comment by deadYokai** [comment]
> @@ ![image](https://private-user-images.githubusercontent.com/171554153/356774414-164fbdc4-8e57-429f-93a9-bd4e3ca8ad51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNTM2NzEsIm5iZiI6MTcyMzI1MzM3MSwicGF0aCI6Ii8xNzE1NTQxNTMvMzU2Nzc0NDE0LTE2NGZiZGM0LThlNTctNDI5Zi05M2E5LWJkNGUzY2E4YWQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQwMTI5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTk5MjVkNjI5NDAxOWVkNmQzYTEzM2I1OGUzYTU3Y2ViZGVkODgyNjdmMDVkNWE3OTY4MTVhMDMxNTIzNTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z53MK1F-4fnldI9phGGya8UxalC3q-iDAlBQPP2ZMV0)

windows related, but I'll see what I can do about it.

**Comment by deadYokai** [comment]
in some textures not recognizing all mipmaps

**Comment by locsucc** [comment]
could u explain detailed how to use fontEdit?

**Comment by deadYokai** [comment]
> could u explain detailed how to use fontEdit?

I will rework it for the new format, and write in detail how to modify the fonts in the [wiki page](https://github.com/deadYokai/dishonored-toolkit/wiki/Font-Editing-(Font))

**Comment by locsucc** [comment]
lysm bro <33

**Comment by deadYokai** [comment]
> lysm bro <33

I would be grateful if you could make a new issue if it's about a different topic, so as not to cause confusion. 

And yes, view a [wiki page](https://github.com/deadYokai/dishonored-toolkit/wiki/Font-Editing-(Font)), 
With SwfMovie fonts, i'll write a tutorial later (i'm little tired)
